application: airconsole-games
version: pong
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_dir: static

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
